apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elastic-test-4.3
  namespace: marketplace
spec:
  channel: "4.3"
  installPlanApproval: Automatic
  name: elasticsearch-operator
  source: redhat-operators
  sourceNamespace: marketplace
  startingCSV: elasticsearch-operator.4.3.20-202005121847
